---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/k8s.cni.cncf.io/networkattachmentdefinition_v1.json
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vpn
spec:
  config: |-
    {
      "cniVersion": "1.1.0",
      "plugins": [
        {
          "type": "macvlan",
          "master": "bond0.90",
          "mode": "bridge",
          "ipam": {
            "type": "static",
            "routes": [
              { "dst": "0.0.0.0/0", "gw": "192.168.90.1" },
              { "dst": "10.42.0.0/16" },
              { "dst": "10.43.0.0/16" }
            ]
          }
        },
        {
          "type": "sbr"
        }
      ]
    }
